### ISSUE TITLE
Cannot connect to Dynamo Db

### ISSUE THREAD

**Issue by waqasak** [edasque/DynamoDBtoCSV#18]
I have found a below error when run the file

{ [NetworkingError: connect ECONNREFUSED]
  message: 'connect ECONNREFUSED',
  code: 'NetworkingError',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  region: 'eu-central-1',
  hostname: 'dynamodb.eu-central-1.amazonaws.com',
  retryable: true,
  time: Fri Oct 14 2016 10:29:33 GMT+0000 (UTC) }

**Comment by edasque** [comment]
Do you still have the issue? It sounds like your user may not have the rights to access the dB?

**Comment by edasque** [comment]
No response , closing
