### ISSUE TITLE
Limit not working

### ISSUE THREAD

**Issue by msambol** [edasque/DynamoDBtoCSV#20]
Limit does not appear to be working. 

It defaults to 1000 but several of my scans
returned more than 1000.

@edasque

**Comment by edasque** [comment]
I no longer have access to an account with DynamoDB. Please submit a PR or give me access to one if you'd like me to take a look.

**Comment by msambol** [comment]
I'll check it out.

**Comment by msambol** [comment]
Ah, so it does actually work correctly, but because of the following code we essentially ignore the limit. Should I make a PR that removes the limit from the query?

https://github.com/edasque/DynamoDBtoCSV/blob/master/dynamoDBtoCSV.js#L43-L45

**Comment by edasque** [comment]
It's probably best you fork and maintain your own, I can point to yours being in active development.
