### ISSUE TITLE
Nothing happened while executing the backup command

### ISSUE THREAD

**Issue by SqlAdmin** [edasque/DynamoDBtoCSV#26]
Hi,

Im using ubuntu 14.04, 
I did the following steps.

Git clone <repo url>
cd DynamoDBtoCSV/
Edit config.json (IAM key with DynamoDB full access)
apt-get install node
apt-get install npm
npm install

Then, 
My DynamoDB table name is **table**
node dynamoDBtoCSV.js -t table >table.csv 

 but nothing happened while executing the above command.
Find the below snap for your reference. 
![image](https://user-images.githubusercontent.com/16044251/27587658-c7f47c7a-5b62-11e7-8cdc-060fc85c5b02.png)

**Comment by edasque** [comment]
What if you just do:

'''node dynamoDBtoCSV.js -t table'''

What do you see? Do you have a table called table? Does that user have access to it?

**Comment by SqlAdmin** [comment]
Thanks for the prompt response, 
Yes, I have a table called table
And the IAM user has full dynamodb access.

this is the result of the `node dynamoDBtoCSV.js -t table`

![image](https://user-images.githubusercontent.com/16044251/27589870-86a793bc-5b6a-11e7-87be-78f349365cc2.png)

**Comment by SqlAdmin** [comment]
Found some errors in **DynamoDBtoCSV/node_modules/aws-sdk/npm-debug.log**

![image](https://user-images.githubusercontent.com/16044251/27590679-1679fac8-5b6d-11e7-939d-bf736a4deeed.png)

**Comment by edasque** [comment]
I need to look more into it. I don't really have a DynamoDB table anymore but I'll try to create one to improve things. I'll update this issue as I make progress.

**Comment by SqlAdmin** [comment]
Thanks

**Comment by SqlAdmin** [comment]
Edasque,  I did a copy of this repo before a few months ago, and I compared the current dynamoDBtoCSV.js with the old dynamoDBtoCSV.js. I can see many changes on that file. 
So I have replaced dynamoDBtoCSV.js with the old one and it worked. 

I have put this project in my collections and find the dynamoDBtoCSV.js for your reference, 

https://github.com/SqlAdmin/OpenSourceCollections/blob/master/Dynamo2CSV/dynamoDBtoCSV.js

**Comment by edasque** [comment]
Good to hear. I see that you've incorporated my project in your collection. I would advise you to use submodules instead of just copying the files over. Otherwise you'll be versions behind instead of tracking progress. https://github.com/blog/2104-working-with-submodules

**Comment by SqlAdmin** [comment]
Yeah, sure.
