### ISSUE TITLE
Use AWS Credential Provider Chain instead of config.json

### ISSUE THREAD

**Issue by dmarreco** [edasque/DynamoDBtoCSV#49]
I'd like this project to obtain the AWS credentials from the system's credential provider chain (as described in https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html), instead of having to manually set it in config.json.

**Comment by hannahapuan** [comment]
Made a PR for this (#54)

**Comment by edasque** [comment]
Solved with #54
