### ISSUE TITLE
[Bug] Profile aren't properly handled, return wrong credentials

### ISSUE THREAD

**Issue by Vadorequest** [edasque/DynamoDBtoCSV#56]
I won't make a PR because those existing seem dead and don't want to waste my time, but know that the `profile` isn't correctly managed as it is now.

Current version (buggy):
```js
if (program.profile) {
  var newCreds = AWS.config.credentials;
  newCreds.profile = program.profile;
  AWS.config.update({ credentials: newCreds });
}
```

> This doesn't work as expected, it doesn't select the credentials for the right profile but from the first defined profile. It may have worked with a very simple setup (1 profile) but doesn't really handle multi profiles.

---
Fixed version:
```js
if (program.profile) {
  var newCreds = new AWS.SharedIniFileCredentials({ profile: program.profile });
  newCreds.profile = program.profile;
  AWS.config.update({ credentials: newCreds });
}
```

See https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html

**Comment by edasque** [comment]
Thank you, done.

**Comment by Vadorequest** [comment]
Whoa, that was fast. Thanks!
